name: Publish Package to npm

on:
  push:
    branches:
      - main
    paths:
      - 'dist/**'
      - 'package.json'
      - '.changeset/**'
      - '.github/workflows/publish.yml'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org/'
      - run: pnpm install --frozen-lockfile
      - run: pnpm run build
      - name: Version packages and changelog
        run: |
          pnpm changeset version
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "ci: version packages and changelog [skip ci]" || echo "No changes to version"
          git push
      - uses: changesets/action@v1
        with:
          publish: pnpm publish --no-git-checks --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
